/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData img_file = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_arrowleft = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_arrowright = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_bluemondaypan = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmark = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_icon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_illustration_147x141 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_illustration = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_illustration_1 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_trash = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_illustration_206x206 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_illustration_261x277 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_location = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_settings = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData img_volume = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
